# Generated by Django 2.1.3 on 2018-11-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='start_paying',
            new_name='expiration',
        ),
    ]
