# Generated by Django 2.1.3 on 2018-11-20 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20181119_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_number', models.IntegerField()),
                ('detail', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='number_installments',
            new_name='expiration_day',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
        migrations.AddField(
            model_name='bill',
            name='frequency',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='total_installments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill'),
        ),
        migrations.AddField(
            model_name='debt',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.BillStatus'),
        ),
    ]
