# Generated by Django 2.1.3 on 2018-11-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20181119_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency_code',
            field=models.CharField(default='ARS', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=10),
            preserve_default=False,
        ),
    ]
